# Generated by Django 5.2.4 on 2025-07-29 09:50

import delivery_partners.models
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery_Partners',
            fields=[
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('pending_payout', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('wallet_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('last_payout_date', models.DateTimeField(blank=True, null=True)),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage of commission deducted from each payout', max_digits=5)),
                ('is_commission_fixed', models.BooleanField(default=True, help_text='Is this a fixed or variable commission?')),
                ('payout_frequency', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly')], default='weekly', max_length=10)),
                ('partner_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='^\\+?\\d{10,15}$')])),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('max_orders', models.PositiveIntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryPerson',
            fields=[
                ('person_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_available', models.BooleanField(default=True)),
                ('vehicle_number', models.CharField(max_length=20, unique=True, validators=[delivery_partners.models.DeliveryPerson.validate_vehicle_number])),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('picked_up', 'Picked Up'), ('delivered', 'Delivered'), ('returned', 'Returned')], default='idle', max_length=20)),
            ],
        ),
    ]
