# Generated by Django 5.2.4 on 2025-08-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery_partners', '0001_initial'),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_partners',
            name='assigned_restaurants',
            field=models.ManyToManyField(related_name='delivery_partners', to='restaurants.restaurant'),
        ),
    ]
