# Generated by Django 5.2.4 on 2025-07-29 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery_partners', '0002_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_partners',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_partner_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryperson',
            name='assigned_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_person', to='orders.orders'),
        ),
        migrations.AddField(
            model_name='deliveryperson',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_persons', to='delivery_partners.delivery_partners'),
        ),
        migrations.AddField(
            model_name='deliveryperson',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_person_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
