# Generated by Django 5.2.4 on 2025-07-22 06:59

import delivery_partners.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_partners', '0002_initial'),
        ('orders', '0005_orders_cancelled_reason_orders_delivered_to_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery_partners',
            name='vehicle_number',
        ),
        migrations.CreateModel(
            name='DeliveryPerson',
            fields=[
                ('person_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_available', models.BooleanField(default=True)),
                ('vehicle_number', models.CharField(max_length=20, unique=True, validators=[delivery_partners.models.DeliveryPerson.validate_vehicle_number])),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('picked_up', 'Picked Up'), ('en_route', 'En Route'), ('delivered', 'Delivered'), ('returned', 'Returned')], default='idle', max_length=20)),
                ('assigned_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_person', to='orders.orders')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_persons', to='delivery_partners.delivery_partners')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_person_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
