# Generated by Django 5.2.4 on 2025-07-22 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_partners', '0003_remove_delivery_partners_vehicle_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryperson',
            name='user',
        ),
    ]
