# Generated by Django 5.2.3 on 2025-07-03 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('restaurants', '0002_remove_restaurantsmodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersmodel',
            name='restaurant_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='restaurants.restaurantsmodel'),
        ),
    ]
