# Generated by Django 5.2.3 on 2025-07-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_ordersmodel_restaurant_id'),
        ('restaurants', '0002_remove_restaurantsmodel_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersmodel',
            name='restaurant_id',
        ),
        migrations.AlterField(
            model_name='ordersmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('out_for_delivery', 'Out_for_Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='ordersmodel',
            name='restaurant_id',
            field=models.ManyToManyField(related_name='order', to='restaurants.restaurantsmodel'),
        ),
    ]
