# Generated by Django 5.2.3 on 2025-07-10 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='authentication',
        ),
    ]
