# Generated by Django 5.2.4 on 2025-07-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Customer', 'Customer'), ('RestaurantOwner', 'RestaurantOwner'), ('admin', 'Admin'), ('deliverypartner', 'DeliveryPartner')], default='Customer', max_length=20),
        ),
    ]
