# Generated by Django 5.2.4 on 2025-07-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Customer', 'Customer'), ('RestaurantOwner', 'RestaurantOwner'), ('admin', 'Admin'), ('deliverypartner', 'DeliveryPartner'), ('deliveryperson', 'DeliveryPerson')], default='Customer', max_length=20),
        ),
    ]
