# Generated by Django 5.2.4 on 2025-08-07 05:40

import common.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=common.base.upload_to),
        ),
    ]
