# Generated by Django 5.2.4 on 2025-07-17 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
        ('user', '0004_savedaddress_favorite_only_one_of_menu_or_restaurant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='applied_coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coupons.coupon'),
        ),
    ]
