# Generated by Django 5.2.4 on 2025-08-07 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedaddress',
            name='address_line1',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='address_line1',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
