# Generated by Django 5.2.4 on 2025-08-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='calling_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='region',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
