# Generated by Django 5.2.4 on 2025-08-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_region_calling_code_alter_region_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='calling_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='region',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
