# Generated by Django 5.2.4 on 2025-07-16 07:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
        ('restaurants', '0006_alter_menuitem_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'menu_item'), ('user', 'restaurant')},
        ),
    ]
