# Generated by Django 5.2.3 on 2025-07-03 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantsmodel',
            name='description',
        ),
    ]
