# Generated by Django 5.2.3 on 2025-07-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_ordersmodel_restaurant_id_and_more'),
        ('restaurants', '0002_remove_restaurantsmodel_description'),
        ('user', '0002_rename_user_userclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItems',
            fields=[
                ('m_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('m_name', models.CharField(max_length=100)),
                ('m_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('m_is_available', models.BooleanField(default=True)),
                ('m_category', models.CharField(max_length=50)),
                ('m_created_at', models.DateTimeField(auto_now_add=True)),
                ('m_restaurant_id', models.ManyToManyField(blank=True, related_name='item', to='restaurants.restaurantsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('c_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('c_quantity', models.IntegerField()),
                ('c_created_at', models.DateTimeField(auto_now_add=True)),
                ('c_user_id', models.ManyToManyField(related_name='rating2', to='user.userclass')),
                ('c_MenuItems_id', models.ManyToManyField(related_name='item_rating2', to='restaurants.menuitems')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('o_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('o_quantity', models.IntegerField()),
                ('o_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('o_order_id', models.ManyToManyField(related_name='orderItem1', to='orders.ordersmodel')),
                ('o_user_id', models.ManyToManyField(related_name='order1', to='user.userclass')),
            ],
        ),
        migrations.CreateModel(
            name='rating',
            fields=[
                ('r_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('r_rating', models.IntegerField()),
                ('r_review', models.TextField()),
                ('r_created_at', models.DateTimeField(auto_now_add=True)),
                ('r_MenuItems_id', models.ManyToManyField(related_name='item_rating1', to='restaurants.menuitems')),
                ('r_restaurant_id', models.ManyToManyField(blank=True, related_name='item1', to='restaurants.restaurantsmodel')),
                ('r_user_id', models.ManyToManyField(related_name='rating1', to='user.userclass')),
            ],
        ),
    ]
