# Generated by Django 5.2.4 on 2025-08-01 12:16

import common.base
import datetime
import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(default=datetime.datetime(2025, 8, 1, 12, 16, 4, 464440, tzinfo=datetime.timezone.utc))),
                ('end_date', models.DateTimeField(default=common.base.TimeRangeMixin.one_day_from_now)),
                ('title', models.CharField(max_length=255)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address_line1', models.CharField(max_length=150, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=150, null=True)),
                ('pincode', models.IntegerField(null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('label', models.CharField(default='Home', help_text='e.g., Home, Work', max_length=50)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('pan_card', models.CharField(max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid PAN card number', regex='^[A-Z]{5}[0-9]{4}[A-Z]$')])),
                ('gst_number', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid GST number', regex='^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$')])),
                ('fssai_license', models.CharField(max_length=14, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 14-digit FSSAI license number', regex='^\\d{14}$')])),
                ('menu_image', models.ImageField(blank=True, null=True, upload_to='restaurant/menus/')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='restaurant/profiles/')),
                ('payout_frequency', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], default='monthly', max_length=10)),
                ('payment_method_preference', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('upi', 'UPI')], default='bank_transfer', max_length=20)),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=10.0, help_text='Commission deducted from restaurant earnings', max_digits=5)),
                ('account_holder_name', models.CharField(max_length=100, null=True)),
                ('account_number', models.CharField(max_length=20, null=True)),
                ('ifsc_code', models.CharField(max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid IFSC code', regex='^[A-Z]{4}0[A-Z0-9]{6}$')])),
                ('bank_name', models.CharField(max_length=100, null=True)),
                ('upi_id', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('restaurant_primary_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IN', unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('is_open', models.BooleanField(default=True)),
                ('restaurant_type', models.CharField(choices=[('veg', 'Vegetarian'), ('nonveg', 'Non-Vegetarian'), ('both', 'Both')], default='both', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Restaurants',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('name', models.CharField(max_length=100)),
                ('is_available', models.BooleanField(default=True)),
                ('item_type', models.CharField(choices=[('veg', 'Vegetarian'), ('nonveg', 'Non-Vegetarian'), ('both', 'Both')], default='both', max_length=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_item_category', to='restaurants.category')),
            ],
        ),
    ]
