# Generated by Django 5.2.4 on 2025-07-15 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_restaurants_owner_alter_restaurants_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
