# Generated by Django 5.2.4 on 2025-08-02 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_alter_offer_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 2, 17, 37, 47, 53713, tzinfo=datetime.timezone.utc)),
        ),
    ]
