# Generated by Django 5.2.4 on 2025-08-02 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_alter_offer_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 2, 18, 17, 19, 301445, tzinfo=datetime.timezone.utc)),
        ),
    ]
