# Generated by Django 5.2.4 on 2025-07-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_alter_restaurants_city_alter_restaurants_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
