# Generated by Django 5.2.4 on 2025-07-16 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_alter_menuitem_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menuitem',
            unique_together={('restaurant', 'name')},
        ),
    ]
