# Generated by Django 5.2.4 on 2025-07-17 07:29

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 18, 7, 29, 5, 310258, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='offer',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
