# Generated by Django 5.2.4 on 2025-08-03 05:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_alter_offer_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 3, 5, 12, 11, 227572, tzinfo=datetime.timezone.utc)),
        ),
    ]
