# Generated by Django 5.2.4 on 2025-07-17 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_alter_offer_end_time_alter_offer_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 18, 10, 5, 16, 734284, tzinfo=datetime.timezone.utc)),
        ),
    ]
