# Generated by Django 5.2.4 on 2025-07-17 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_alter_offer_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 18, 10, 28, 9, 453961, tzinfo=datetime.timezone.utc)),
        ),
    ]
