# Generated by Django 5.2.4 on 2025-07-17 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_alter_offer_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 18, 11, 33, 40, 976996, tzinfo=datetime.timezone.utc)),
        ),
    ]
