# Generated by Django 5.2.4 on 2025-08-03 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0012_alter_offer_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 3, 10, 0, 39, 907783, tzinfo=datetime.timezone.utc)),
        ),
    ]
