# Generated by Django 5.2.4 on 2025-07-21 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0015_alter_offer_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 22, 11, 45, 14, 185713, tzinfo=datetime.timezone.utc)),
        ),
    ]
