# Generated by Django 5.2.4 on 2025-08-04 06:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0016_alter_offer_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 4, 6, 46, 22, 320936, tzinfo=datetime.timezone.utc)),
        ),
    ]
