# Generated by Django 5.2.4 on 2025-08-04 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0018_alter_restaurant_options_restaurant_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 4, 9, 13, 9, 208144, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterUniqueTogether(
            name='restaurant',
            unique_together={('name', 'address_line1')},
        ),
    ]
