# Generated by Django 5.2.4 on 2025-08-04 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0019_alter_offer_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 4, 9, 13, 28, 289797, tzinfo=datetime.timezone.utc)),
        ),
    ]
