# Generated by Django 5.2.4 on 2025-08-04 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0020_alter_offer_start_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'permissions': [('can_approve_item', 'Can approve item')]},
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='offer',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 4, 11, 11, 17, 173310, tzinfo=datetime.timezone.utc)),
        ),
    ]
