# Generated by Django 5.2.4 on 2025-07-22 07:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0020_alter_offer_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 23, 7, 15, 24, 168381, tzinfo=datetime.timezone.utc)),
        ),
    ]
