# Generated by Django 5.2.4 on 2025-08-04 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0021_alter_menuitem_options_menuitem_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 4, 11, 11, 31, 434960, tzinfo=datetime.timezone.utc)),
        ),
    ]
