# Generated by Django 5.2.4 on 2025-08-04 12:34

import common.base
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0022_alter_offer_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image file (JPEG, PNG, etc.)', max_length=255, null=True, upload_to=common.base.upload_to),
        ),
        migrations.AlterField(
            model_name='offer',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 4, 12, 34, 18, 1013, tzinfo=datetime.timezone.utc)),
        ),
    ]
