# Generated by Django 5.2.4 on 2025-08-04 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0023_alter_menuitem_image_alter_offer_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 4, 13, 13, 36, 655949, tzinfo=datetime.timezone.utc)),
        ),
    ]
