# Generated by Django 5.2.4 on 2025-08-05 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0025_alter_menuitem_image_alter_offer_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 5, 12, 54, 48, 868529, tzinfo=datetime.timezone.utc)),
        ),
    ]
