# Generated by Django 5.2.4 on 2025-08-05 16:00

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_region_calling_code_alter_region_code_and_more'),
        ('restaurants', '0027_alter_offer_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='business_phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='region',
            field=models.ForeignKey(default=1, help_text='Determines valid phone number format', on_delete=django.db.models.deletion.PROTECT, related_name='restaurants', to='common.region'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 5, 15, 56, 37, 455839, tzinfo=datetime.timezone.utc)),
        ),
    ]
