# Generated by Django 5.2.4 on 2025-08-05 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0028_restaurant_business_phone_restaurant_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 5, 17, 11, 52, 810183, tzinfo=datetime.timezone.utc)),
        ),
    ]
