# Generated by Django 5.2.4 on 2025-08-05 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0030_alter_restaurant_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 5, 17, 29, 54, 543612, tzinfo=datetime.timezone.utc)),
        ),
    ]
