# Generated by Django 5.2.4 on 2025-08-05 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0032_alter_offer_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='userProfile/'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 5, 18, 12, 26, 250616, tzinfo=datetime.timezone.utc)),
        ),
    ]
