# Generated by Django 5.2.4 on 2025-08-06 06:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0033_alter_menuitem_image_alter_offer_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 6, 6, 48, 1, 15647, tzinfo=datetime.timezone.utc)),
        ),
    ]
