# Generated by Django 5.2.4 on 2025-08-06 07:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0035_alter_offer_start_date_alter_restaurant_pan_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 6, 7, 45, 41, 17019, tzinfo=datetime.timezone.utc)),
        ),
    ]
