# Generated by Django 5.2.4 on 2025-08-06 07:50

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0036_alter_offer_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 6, 7, 49, 42, 278799, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='account_holder_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='account_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='bank_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='fssai_license',
            field=models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message='Enter a valid 14-digit FSSAI license number', regex='^\\d{14}$')]),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='gst_number',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid GST number', regex='^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$')]),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='menu_image',
            field=models.ImageField(blank=True, upload_to='restaurant/menus/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='restaurant/profiles/'),
        ),
    ]
