# Generated by Django 5.2.4 on 2025-08-06 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0037_alter_offer_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 6, 7, 54, 3, 792876, tzinfo=datetime.timezone.utc)),
        ),
    ]
