# Generated by Django 5.2.4 on 2025-08-06 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0039_alter_offer_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='account_holder_name',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='ifsc_code',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='upi_id',
        ),
        migrations.AlterField(
            model_name='offer',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 6, 7, 57, 51, 829449, tzinfo=datetime.timezone.utc)),
        ),
    ]
