# Generated by Django 5.2.4 on 2025-08-06 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0040_remove_restaurant_account_holder_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 6, 7, 59, 22, 635912, tzinfo=datetime.timezone.utc)),
        ),
    ]
