# Generated by Django 5.2.4 on 2025-08-06 08:02

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0041_alter_offer_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='account_holder_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='account_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='bank_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='ifsc_code',
            field=models.CharField(max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid IFSC code', regex='^[A-Z]{4}0[A-Z0-9]{6}$')]),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='upi_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 6, 8, 2, 45, 434260, tzinfo=datetime.timezone.utc)),
        ),
    ]
