# Generated by Django 5.2.4 on 2025-08-06 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0042_restaurant_account_holder_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 6, 8, 7, 16, 126745, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='business_phone',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
