# Generated by Django 5.2.4 on 2025-08-06 09:43

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0045_alter_offer_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 6, 9, 43, 38, 997153, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='fssai_license',
            field=models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 14-digit FSSAI license number', regex='^\\d{14}$')]),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='gst_number',
            field=models.CharField(blank=True, max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid GST number', regex='^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$')]),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='pan_card',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid PAN card number', regex='^[A-Z]{5}[0-9]{4}[A-Z]$')]),
        ),
    ]
