# Generated by Django 5.2.4 on 2025-08-07 06:15

import common.base
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0047_alter_offer_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=common.base.upload_to),
        ),
        migrations.AlterField(
            model_name='offer',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 7, 6, 15, 14, 943283, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address_line1',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
