# Generated by Django 5.2.4 on 2025-08-07 06:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0048_alter_menuitem_image_alter_offer_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 7, 6, 34, 22, 219000, tzinfo=datetime.timezone.utc)),
        ),
    ]
