# Generated by Django 5.2.4 on 2025-08-12 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0050_alter_offer_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 12, 11, 44, 45, 174082, tzinfo=datetime.timezone.utc)),
        ),
    ]
