# Generated by Django 5.2.4 on 2025-07-21 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 22, 8, 52, 57, 15696, tzinfo=datetime.timezone.utc)),
        ),
    ]
