# Generated by Django 5.2.4 on 2025-07-17 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_alter_coupon_end_time_alter_coupon_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 18, 11, 43, 38, 543404, tzinfo=datetime.timezone.utc)),
        ),
    ]
