# Generated by Django 5.2.4 on 2025-08-02 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 3, 17, 35, 48, 171932, tzinfo=datetime.timezone.utc)),
        ),
    ]
