# Generated by Django 5.2.4 on 2025-07-21 09:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0004_alter_coupon_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 22, 9, 31, 28, 299085, tzinfo=datetime.timezone.utc)),
        ),
    ]
