# Generated by Django 5.2.4 on 2025-08-02 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0005_alter_coupon_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 3, 18, 17, 19, 311165, tzinfo=datetime.timezone.utc)),
        ),
    ]
