# Generated by Django 5.2.4 on 2025-07-21 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0006_alter_coupon_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 22, 10, 27, 24, 653387, tzinfo=datetime.timezone.utc)),
        ),
    ]
