# Generated by Django 5.2.4 on 2025-08-03 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0012_alter_coupon_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 4, 7, 47, 18, 333636, tzinfo=datetime.timezone.utc)),
        ),
    ]
