# Generated by Django 5.2.4 on 2025-08-03 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0015_alter_coupon_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 4, 10, 34, 41, 836730, tzinfo=datetime.timezone.utc)),
        ),
    ]
