# Generated by Django 5.2.4 on 2025-08-03 15:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0016_alter_coupon_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 4, 15, 42, 22, 96017, tzinfo=datetime.timezone.utc)),
        ),
    ]
