# Generated by Django 5.2.4 on 2025-07-21 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0017_alter_coupon_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 22, 12, 9, 55, 151569, tzinfo=datetime.timezone.utc)),
        ),
    ]
