# Generated by Django 5.2.4 on 2025-08-04 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0018_alter_coupon_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 5, 8, 52, 0, 742594, tzinfo=datetime.timezone.utc)),
        ),
    ]
