# Generated by Django 5.2.4 on 2025-07-22 06:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0019_alter_coupon_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 23, 6, 59, 22, 180239, tzinfo=datetime.timezone.utc)),
        ),
    ]
