# Generated by Django 5.2.4 on 2025-07-22 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0020_alter_coupon_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 23, 7, 0, 31, 728770, tzinfo=datetime.timezone.utc)),
        ),
    ]
