# Generated by Django 5.2.4 on 2025-08-04 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0020_alter_coupon_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 5, 9, 13, 28, 303903, tzinfo=datetime.timezone.utc)),
        ),
    ]
