# Generated by Django 5.2.4 on 2025-07-22 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0024_alter_coupon_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 23, 8, 52, 3, 30104, tzinfo=datetime.timezone.utc)),
        ),
    ]
