# Generated by Django 5.2.4 on 2025-08-04 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0025_alter_coupon_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 5, 15, 48, 57, 800930, tzinfo=datetime.timezone.utc)),
        ),
    ]
