# Generated by Django 5.2.4 on 2025-08-05 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0026_alter_coupon_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 6, 12, 54, 48, 881495, tzinfo=datetime.timezone.utc)),
        ),
    ]
