# Generated by Django 5.2.4 on 2025-08-05 16:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0028_alter_coupon_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 6, 15, 56, 37, 467655, tzinfo=datetime.timezone.utc)),
        ),
    ]
