# Generated by Django 5.2.4 on 2025-08-05 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0030_alter_coupon_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 6, 17, 25, 28, 687376, tzinfo=datetime.timezone.utc)),
        ),
    ]
