# Generated by Django 5.2.4 on 2025-08-05 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0032_alter_coupon_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 6, 17, 33, 4, 230092, tzinfo=datetime.timezone.utc)),
        ),
    ]
