# Generated by Django 5.2.4 on 2025-08-05 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0033_alter_coupon_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 6, 18, 12, 26, 264454, tzinfo=datetime.timezone.utc)),
        ),
    ]
