# Generated by Django 5.2.4 on 2025-08-06 06:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0034_alter_coupon_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 7, 6, 48, 1, 26551, tzinfo=datetime.timezone.utc)),
        ),
    ]
