# Generated by Django 5.2.4 on 2025-08-06 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0038_alter_coupon_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 7, 7, 54, 3, 804197, tzinfo=datetime.timezone.utc)),
        ),
    ]
