# Generated by Django 5.2.4 on 2025-08-06 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0044_alter_coupon_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 7, 9, 25, 10, 724515, tzinfo=datetime.timezone.utc)),
        ),
    ]
