# Generated by Django 5.2.4 on 2025-08-07 05:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0047_alter_coupon_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 8, 5, 40, 41, 29202, tzinfo=datetime.timezone.utc)),
        ),
    ]
