# Generated by Django 5.2.4 on 2025-08-07 06:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0048_alter_coupon_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 8, 6, 15, 14, 947380, tzinfo=datetime.timezone.utc)),
        ),
    ]
