# Generated by Django 5.2.4 on 2025-08-12 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0050_alter_coupon_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 13, 10, 30, 50, 790419, tzinfo=datetime.timezone.utc)),
        ),
    ]
