# Generated by Django 5.2.4 on 2025-07-29 09:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('payment_method_id', models.UUIDField(default=uuid.UUID('284710cd-d8ab-409d-bf46-f66b3e60a8cb'), editable=False, unique=True)),
                ('payment_method_type', models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('upi', 'UPI (e.g., Google Pay, PhonePe)'), ('netbanking', 'Net Banking'), ('wallet', 'Digital Wallet (Paytm, Amazon Pay)'), ('cash_on_delivery', 'Cash on Delivery'), ('razor_pay', 'Razor Pay')], default='cash_on_delivery', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending Authorization'), ('authorized', 'Authorized'), ('captured', 'Captured'), ('failed', 'Failed'), ('refund_initiated', 'Refund Initiated'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('payment_authorized_at', models.DateTimeField(blank=True, null=True)),
                ('payment_captured_at', models.DateTimeField(blank=True, null=True)),
                ('gateway_reference_id', models.UUIDField(blank=True, null=True)),
                ('merchant_reference_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('gateway_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_live_mode', models.BooleanField(default=False)),
                ('gateway_name', models.CharField(blank=True, max_length=50, null=True)),
                ('amount_authorized', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('amount_captured', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('amount_refunded', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_address', models.TextField()),
                ('order_code', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('applied_coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coupons.coupon')),
            ],
            options={
                'verbose_name_plural': 'Cart Items',
            },
        ),
    ]
