# Generated by Django 5.2.3 on 2025-07-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='restaurant_id',
            field=models.ManyToManyField(related_name='order', to='restaurants.restaurants'),
        ),
    ]
