# Generated by Django 5.2.4 on 2025-08-06 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0035_alter_coupon_end_time'),
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='applied_coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart', to='coupons.coupon'),
        ),
    ]
