# Generated by Django 5.2.4 on 2025-07-21 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='cancelled_reason',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='delivered_to_user',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='picked_by_partner',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='restaurant_ready',
        ),
    ]
