# Generated by Django 5.2.4 on 2025-07-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_orders_cancelled_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='cancelled_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='delivered_to_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='picked_by_partner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='restaurant_ready',
            field=models.BooleanField(default=False),
        ),
    ]
