version: '3.8'

services:

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  django:
    container_name: django
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
    - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
