version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=FoodDelivery
      - POSTGRES_USER=foodDeliveryUser
      - POSTGRES_PASSWORD=raju
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:16.9
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=FoodDelivery
      - POSTGRES_USER=foodDeliveryUser
      - POSTGRES_PASSWORD=raju
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
