# Generated by Django 5.2.3 on 2025-07-02 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='userClass',
        ),
    ]
